package io.github.adaptivekt.core

import androidx.compose.ui.graphics.Color

public data class AdaptiveColorScheme(
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceMuted: Color,
    val border: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textInverse: Color,
    val primary: Color,
    val primarySubtle: Color,
    val primaryText: Color,
    val success: Color,
    val successSubtle: Color,
    val successText: Color,
    val warning: Color,
    val warningSubtle: Color,
    val warningText: Color,
    val danger: Color,
    val dangerSubtle: Color,
    val dangerText: Color,
    val info: Color,
    val infoSubtle: Color,
    val infoText: Color,
    val disabledBackground: Color,
    val disabledText: Color,
    val focusRing: Color,
    val overlay: Color,
)

public object AdaptiveColorSchemes {
    public fun defaultLight(): AdaptiveColorScheme = AdaptiveColorScheme(
        background = Color(0xFFF8FAFC),
        surface = Color.White,
        surfaceRaised = Color.White,
        surfaceMuted = Color(0xFFF8FAFC),
        border = Color(0xFFE2E8F0),
        borderStrong = Color(0xFFCBD5E1),
        textPrimary = Color(0xFF0F172A),
        textSecondary = Color(0xFF334155),
        textMuted = Color(0xFF64748B),
        textInverse = Color.White,
        primary = Color(0xFF2563EB),
        primarySubtle = Color(0xFFEBF4FF),
        primaryText = Color(0xFF1E3A8A),
        success = Color(0xFF047857),
        successSubtle = Color(0xFFF0FDF4),
        successText = Color(0xFF065F46),
        warning = Color(0xFFB45309),
        warningSubtle = Color(0xFFFDF6E7),
        warningText = Color(0xFF92400E),
        danger = Color(0xFFB91C1C),
        dangerSubtle = Color(0xFFFEF2F2),
        dangerText = Color(0xFF991B1B),
        info = Color(0xFF1D4ED8),
        infoSubtle = Color(0xFFEFF6FF),
        infoText = Color(0xFF3730A3),
        disabledBackground = Color(0xFFF1F5F9),
        disabledText = Color(0xFF94A3B8),
        focusRing = Color(0xFF2563EB),
        overlay = Color(0x660F172A),
    )

    public fun defaultDark(): AdaptiveColorScheme = AdaptiveColorScheme(
        background = Color(0xFF0B1120),
        surface = Color(0xFF111827),
        surfaceRaised = Color(0xFF172033),
        surfaceMuted = Color(0xFF0F172A),
        border = Color(0xFF263244),
        borderStrong = Color(0xFF3B4A60),
        textPrimary = Color(0xFFF8FAFC),
        textSecondary = Color(0xFFCBD5E1),
        textMuted = Color(0xFF94A3B8),
        textInverse = Color(0xFF0F172A),
        primary = Color(0xFF60A5FA),
        primarySubtle = Color(0xFF1E3A5F),
        primaryText = Color(0xFFBFDBFE),
        success = Color(0xFF34D399),
        successSubtle = Color(0xFF123D32),
        successText = Color(0xFFA7F3D0),
        warning = Color(0xFFFBBF24),
        warningSubtle = Color(0xFF49351A),
        warningText = Color(0xFFFDE68A),
        danger = Color(0xFFF87171),
        dangerSubtle = Color(0xFF4B1D24),
        dangerText = Color(0xFFFECACA),
        info = Color(0xFF93C5FD),
        infoSubtle = Color(0xFF1E2F55),
        infoText = Color(0xFFBFDBFE),
        disabledBackground = Color(0xFF1F2937),
        disabledText = Color(0xFF64748B),
        focusRing = Color(0xFF93C5FD),
        overlay = Color(0x99000000),
    )
}
